version: '3'
services:
  db:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
  redis:
    image: redis:6.2.6-alpine3.14
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - redis_volume:/data
volumes:
  postgres_volume:
  redis_volume: